apiVersion: v1
kind: Namespace
metadata:
  name: asm-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: tekton
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
